apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: '^7.0.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: grafana
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: cluster-values
      valuesKey: values.yaml
