apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: k8s-monitoring
      version: '^2.0.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: monitoring
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: cluster-values
      valuesKey: values.yaml
