apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - helmrelease.yaml


configMapGenerator:
  - name: cluster-values
    files:
      - values.yaml=values.yaml