apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - helmrelease.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: cluster-values
    namespace: monitoring
    files:
      - values.yaml=values.yaml