---
cluster:
  name: cluster-metrics-cluster

destinations:
  - name: prometheus
    type: prometheus
    url: http://mimir-nginx.mimir.svc:80/api/v1/push
  - name: loki
    type: loki
    url: http://loki.loki.svc:3100/api/push

# Features
clusterEvents:
  enabled: true

clusterMetrics:
  enabled: true
  controlPlane:
    enabled: true

podLogs:
  enabled: false


# Collectors
alloy-metrics:
  enabled: true

alloy-logs:
  enabled: false

alloy-singleton:
  enabled: true
prometheusOperatorObjects:
  enabled: true