apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir
  namespace: mimir
spec:
  interval: 5m
  chart:
    spec:
      chart: mimir-distributed
      version: '^5.0.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-mimir
        namespace: mimir
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: cluster-values
      valuesKey: values.yaml
